/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
  var city = $(this).text() ; 
  $.ajax('https://query.yahooapis.com/v1/public/yql', {
   method: 'GET',
   data: {
     q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
     format: 'json'
   },
   success: function (data) {
     alert("success") ; 
    

      var weatherInfo = data.query.results.channel;
      var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
      var noCity = 'Sorry, I found no city matching ' + city;
      if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
      var date = data.query.results.channel.item.condition.date;  
       return false;
      }
      console.log(weatherInfo);

      $('.temperature').text(weatherInfo.item.condition.temp);
      $('.des').text(weatherInfo.item.condition.text);
      $('.date').text(weatherInfo.item.condition.date);
      $('#date1').text(weatherInfo.item.forecast[1].date);
      $('#date2').text(weatherInfo.item.forecast[2].date);
      $('#date3').text(weatherInfo.item.forecast[3].date);
      $('#tem1').text(weatherInfo.item.forecast[1].high);
      $('#tem2').text(weatherInfo.item.forecast[2].high);
      $('#tem3').text(weatherInfo.item.forecast[3].high);
      console.log(cityMatch);
      //console.log(noCity);
   }
 });

});
